name: Catalog Service CI/CD

on:
  push:
    paths:
      - "microservices_project/catalog_service/**"
      - ".github/workflows/catalog-ci.yml"

jobs:

  build-and-push-to-yc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build \
          -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/catalog-service:latest \
          microservices_project/catalog_service

    - name: Login to YC Registry
      uses: docker/login-action@v3
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YC_KEYS }}

    - name: Push image
      run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/catalog-service:latest


  deploy:
    name: Deploy Serverless Container
    runs-on: ubuntu-latest
    needs: build-and-push-to-yc

    steps:
    - name: Deploy serverless container
      uses: yc-actions/yc-sls-container-deploy@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
        container-name: ${{ secrets.YC_CONTAINER_NAME }}
        folder-id: ${{ secrets.YC_FOLDER_ID }}
        revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/catalog-service:latest
        revision-service-account-id: ${{ secrets.YC_SA_ID }}
        revision-env: |
          AMQP_URL=${{ secrets.ENV_AMQP_URL }}
          POSTGRES_URL=${{ secrets.ENV_POSTGRES_URL }}
